site_name: Repository
site_url: https://docs.ethantwardy.com
site_dir: build
theme:
  name: material
  features:
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: 'sources'
      check_paths: true
  - markdown.extensions.admonition
